import { useEffect, useState } from 'react';
import './App.css'

function App() {
  const [links, setLinks] = useState("");

  useEffect(() => {
    if (!links) {

      const val1 = import.meta.env.VITE_VAL1;
      const val2 = import.meta.env.VITE_VAL2;

      //unecessary link ascii encoding/decoding for run...
      // const val1Arry = new Uint8Array(val1.split(',').map(x => Number(x)));
      // const decodedVal1 = new TextDecoder().decode(val1Arry);
      setLinks([val1, val2]);
    }
  }, [links]);

  return (
    <>
      <div className="card">
        <div className="cardDate">3/3/2025</div>
        <div style={{ display: 'inline' }}>
          <a className="carda" href={links[0]}>
            aMazeThing
          </a>
          &nbsp;--&nbsp;
          <a className="carda" href={links[1]}>
            code
          </a>
        </div>
        <p>
          aMazeThing is a React Typescript AWS CloudFront powered website that give users endless mazes to solve over and over again!
          <br /><br />
          Users may select from replayable daily mazes that are generated by a AWS CDK Stack utilizing: Lambda, S3 Bucket, and EventBridge Scheduler.
          <br /><br />
          A daily maze is generated using an EventBridge Schedule Rule that triggers a Lambda function every 24 hours that writes to a S3 Bucket. The CloudFront site then reads mazes from the last ten days for users to select. Or a user may use the embedded TypeScript maze generator as many times as they want.

          <a>
            {/* aMazeThing Medium blog with more passion :) */}
          </a>

        </p>
      </div>
      <div className="card"><a>
        <div className="cardDate">x/x/2025</div>
        Incomming Soon!
      </a></div>
      <p className="read-the-docs">
        Github Pages Website for showcasing some projects, blogs, and more
        <br />
        - Paul Basinger
      </p>
    </>

  )
}

export default App
